// Achievement badges. Each badge has a `check(stats)` predicate that receives a
// computed stats object (see AppContext.getAchievementStats) and returns true
// when the badge should be unlocked. Keeping the logic here makes it trivial to
// add new badges without touching the UI.

export const BADGES = [
  {
    id: 'streak7',
    emoji: '🔥',
    title: '7-Day Streak',
    description: 'Completed your day 7 days in a row.',
    check: (s) => s.longestStreak >= 7,
  },
  {
    id: 'streak30',
    emoji: '🌟',
    title: '30-Day Streak',
    description: 'A full month of consistency.',
    check: (s) => s.longestStreak >= 30,
  },
  {
    id: 'focus20h',
    emoji: '⏳',
    title: 'First 20 Focused Hours',
    description: 'Logged 20 hours of focused work.',
    check: (s) => s.totalFocusMinutes >= 20 * 60,
  },
  {
    id: 'skills10',
    emoji: '🧠',
    title: '10 Skills Learned',
    description: 'Logged 10 new skills.',
    check: (s) => s.totalSkills >= 10,
  },
  {
    id: 'perfectDay',
    emoji: '💯',
    title: 'Perfect Day',
    description: 'Completed 100% of a day’s blocks.',
    check: (s) => s.perfectDays >= 1,
  },
  {
    id: 'project7',
    emoji: '🚀',
    title: 'Project Machine',
    description: '3+ project hours, 7 days in a row.',
    check: (s) => s.longestProjectStreak >= 7,
  },
  {
    id: 'focus50h',
    emoji: '🏆',
    title: '50 Focused Hours',
    description: 'Logged 50 hours of deep work.',
    check: (s) => s.totalFocusMinutes >= 50 * 60,
  },
  {
    id: 'earlyBird',
    emoji: '🌅',
    title: 'Early Bird',
    description: 'Completed the morning routine 5 days running.',
    check: (s) => s.morningStreak >= 5,
  },
  {
    id: 'streak3',
    emoji: '✨',
    title: 'Spark',
    description: 'Got a 3-day streak going.',
    check: (s) => s.longestStreak >= 3,
  },
  {
    id: 'streak14',
    emoji: '⚡',
    title: '2-Week Warrior',
    description: '14-day streak — real momentum.',
    check: (s) => s.longestStreak >= 14,
  },
  {
    id: 'streak100',
    emoji: '💎',
    title: 'Centurion',
    description: 'A 100-day streak. Elite.',
    check: (s) => s.longestStreak >= 100,
  },
  {
    id: 'focus100h',
    emoji: '🧗',
    title: '100 Focused Hours',
    description: 'Logged 100 hours of deep work.',
    check: (s) => s.totalFocusMinutes >= 100 * 60,
  },
  {
    id: 'skills25',
    emoji: '🎓',
    title: '25 Skills Learned',
    description: 'Logged 25 new skills.',
    check: (s) => s.totalSkills >= 25,
  },
  {
    id: 'firstSubmit',
    emoji: '📤',
    title: 'First Submission',
    description: 'Submitted your first piece of finished work.',
    check: (s) => s.totalSubmissions >= 1,
  },
  {
    id: 'submit25',
    emoji: '🗂️',
    title: 'Shipping Machine',
    description: 'Submitted 25 pieces of finished work.',
    check: (s) => s.totalSubmissions >= 25,
  },
  {
    id: 'submit100',
    emoji: '🏭',
    title: 'Relentless',
    description: '100 finished submissions logged.',
    check: (s) => s.totalSubmissions >= 100,
  },
  {
    id: 'bookworm',
    emoji: '🐛',
    title: 'Bookworm',
    description: 'Read 500 pages in total.',
    check: (s) => s.totalPages >= 500,
  },
  {
    id: 'library',
    emoji: '📖',
    title: 'Living Library',
    description: 'Read 2,000 pages in total.',
    check: (s) => s.totalPages >= 2000,
  },
  {
    id: 'readStreak7',
    emoji: '📚',
    title: 'Devoted Reader',
    description: '7 days of reading summaries in a row.',
    check: (s) => s.readingStreak >= 7,
  },
  {
    id: 'milestone5',
    emoji: '🧭',
    title: 'Trailblazer',
    description: 'Completed 5 project milestones.',
    check: (s) => s.milestonesCompleted >= 5,
  },
  {
    id: 'perfectWeek',
    emoji: '🌈',
    title: 'Flawless Seven',
    description: 'Logged 7 perfect (100%) days.',
    check: (s) => s.perfectDays >= 7,
  },
  {
    id: 'points1k',
    emoji: '🪙',
    title: 'Reward Rich',
    description: 'Banked 1,000 reward points.',
    check: (s) => s.rewardPoints >= 1000,
  },
  {
    id: 'planner',
    emoji: '🗺️',
    title: 'The Strategist',
    description: 'Planned tomorrow’s tasks 5 nights running.',
    check: (s) => s.planStreak >= 5,
  },
  {
    id: 'submitStreak10',
    emoji: '📅',
    title: '10-Day Shipper',
    description: 'Submitted work 10 days in a row, no gap.',
    check: (s) => s.submissionStreak >= 10,
  },
  {
    id: 'submitStreak20',
    emoji: '🗓️',
    title: '20-Day Shipper',
    description: '20 straight days of shipping work.',
    check: (s) => s.submissionStreak >= 20,
  },
  {
    id: 'submitStreak25',
    emoji: '📆',
    title: '25-Day Shipper',
    description: '25 straight days of shipping work.',
    check: (s) => s.submissionStreak >= 25,
  },
  {
    id: 'submitStreak50',
    emoji: '🥇',
    title: '50-Day Shipper',
    description: '50 straight days of shipping work.',
    check: (s) => s.submissionStreak >= 50,
  },
]
